### ISSUE TITLE
Torch in requirements.txt is broken

### ISSUE THREAD

**Issue by givemeaname77** [hzwer/ECCV2022-RIFE#209]
I am getting an error saying this
```
ERROR: Could not find a version that satisfies the requirement torch==1.6.0
ERROR: No matching distribution found for torch==1.6.0
```
seems that the torch version mentioned is not right

**Comment by therealkingoftheuniverse** [comment]
Try downgrading to python 3.8.x and use the command: pip install torch==1.6.0 torchvision==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by hzwer** [comment]
What is your python version? I heard the latest version 3.9 seems to be incompatible with the lower version of pytorch.

**Comment by Snamdeo111** [comment]
some versions of torch for windows have been removed from python pip. 

Instead do this go to https://download.pytorch.org/whl/torch_stable.html and then copy the link of torch version you want for your python. finally pip install then the copied link.

example pip install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp36-cp36m-win_amd64.whl. this would solve your problem. same for torchvision

**Comment by givemeaname77** [comment]
running Python 3.9.7 on arch linux

**Comment by givemeaname77** [comment]
> some versions of torch for windows have been removed from python pip.
> 
> Instead do this go to https://download.pytorch.org/whl/torch_stable.html and then copy the link of torch version you want for your python. finally pip install then the copied link.
> 
> example pip install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp36-cp36m-win_amd64.whl. this would solve your problem. same for torchvision

it would be nice if the project can just move on to the latest version of pytorch

**Comment by SomeGuy04** [comment]
> some versions of torch for windows have been removed from python pip.
> 
> Instead do this go to https://download.pytorch.org/whl/torch_stable.html and then copy the link of torch version you want for your python. finally pip install then the copied link.
> 
> example pip install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp36-cp36m-win_amd64.whl. this would solve your problem. same for torchvision

unfortunately this method did not work on Linux(using python3.9)

`
$ pip3 install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp38-cp38-linux_x86_64.whl
Defaulting to user installation because normal site-packages is not writeable
ERROR: torch-1.6.0+cpu-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.
`

**Comment by Snamdeo111** [comment]
> > some versions of torch for windows have been removed from python pip.
> > Instead do this go to https://download.pytorch.org/whl/torch_stable.html and then copy the link of torch version you want for your python. finally pip install then the copied link.
> > example pip install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp36-cp36m-win_amd64.whl. this would solve your problem. same for torchvision
> 
> unfortunately this method did not work on Linux(using python3.9)
> 
> `$ pip3 install https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp38-cp38-linux_x86_64.whl Defaulting to user installation because normal site-packages is not writeable ERROR: torch-1.6.0+cpu-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.`

in the link the cp38 states the python version of 3.8 which will not install on 3.9. look for link with cp39 or just use pip install torch

**Comment by Lightningblade** [comment]
There is no pytorch 1.6.0 version for cp39

**Comment by itsTyrion** [comment]
I just use 3.8. A newer version MAY work, test it, but YMMV

**Comment by awebeer256** [comment]
### Solution
The problem is as follows:
- RIFE requires torch version 1.6 and not anything newer
- torch 1.6 only exists for Python version 3.6 through 3.8
- Some systems ship Python 3.9 or higher by default

So the solution is this:
1. Install Python 3.8 alongside your default Python version.   
   - On Windows, go to [the Python 3.8.10 download page](https://www.python.org/downloads/release/python-3810/), scroll down to the bottom, and download and run the "Windows Installer" that's appropriate for your system (almost certainly 64-bit).
   - On macOS, go to [the Python 3.8.10 download page](https://www.python.org/downloads/release/python-3810/), scroll down to the bottom, and download and run the "macOS 64-bit Intel installer". As that page says, be sure to read and understand the "Important Information" that gets displayed during installation.
   - On Linux, you should try installing it through your package manager.
      - Debian-based distros (Ubuntu, Mint, MX, Zorin, Elementary, Kali, SteamOS, Pop!_OS, …): run `sudo apt-get install python3.8`.
      - RedHat-based distros (Fedora, CentOS, …): run `sudo dnf install python3.8`.
      - If you get an error saying it couldn't find a package by that name, then it's probably been removed from your repos for being too old, and you might be out of luck. In theory you could still build it from source, but according to the readme that might overwrite the `python` and `python3` executable files from your default Python installation.
2. Install the RIFE requirements using Python 3.8
   - Windows:
   ```
   py -3.8 -m ensurepip
   py -3.8 -m pip install --upgrade pip
   py -3.8 -m pip install -r requirements.txt
   ```
   - Linux/macOS:
   ```
   python3.8 -m ensurepip
   python3.8 -m pip install --upgrade pip
   python3.8 -m pip install -r requirements.txt
   ```
3. Run RIFE using Python 3.8
   - Windows: `py -3.8 inference_video.py …`
   - Linux/macOS: `python3.8 inference_video.py …`

**Comment by USMortality** [comment]
Dockerfile should be updated. When building it, it still fails for me on macOS/latest Docker/master.
